const SEVERITY_COLOR = {
  none: 'text-emerald-600',
  mild: 'text-amber-600',
  moderate: 'text-orange-600',
  severe: 'text-red-600',
}

const FITZ_LABEL = {
  I: 'Very fair',
  II: 'Fair',
  III: 'Medium',
  IV: 'Olive / light brown',
  V: 'Brown',
  VI: 'Dark brown / black',
}

export default function ResultCard({ result, onRetake }) {
  return (
    <div className="w-full max-w-sm mx-auto flex flex-col gap-4">
      {result.accuracy_disclaimer && (
        <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3 text-amber-800 text-sm">
          Note: Redness detection may be less accurate for deeper skin tones (Fitzpatrick {result.fitzpatrick_estimate}).
        </div>
      )}

      <div className="bg-white rounded-2xl p-6 flex flex-col gap-4 shadow-sm border border-slate-100">
        <Row label="Skin type" value={result.skin_type} className="capitalize text-slate-900 font-medium" />
        <Row
          label="Acne severity"
          value={result.acne_severity}
          className={`capitalize font-medium ${SEVERITY_COLOR[result.acne_severity] || 'text-slate-900'}`}
        />
        <Row
          label="Skin tone"
          value={`Type ${result.fitzpatrick_estimate} — ${FITZ_LABEL[result.fitzpatrick_estimate] || ''}`}
        />
        <Row
          label="Confidence"
          value={`${Math.round(result.confidence * 100)}%`}
        />

        {result.primary_concerns.length > 0 && (
          <div>
            <p className="text-slate-400 text-xs uppercase tracking-wide mb-2 font-medium">Concerns</p>
            <div className="flex flex-wrap gap-2">
              {result.primary_concerns.map(c => (
                <span key={c} className="bg-slate-100 text-slate-700 text-xs px-3 py-1 rounded-full capitalize">
                  {c}
                </span>
              ))}
            </div>
          </div>
        )}

        <p className="text-slate-400 text-xs border-t border-slate-100 pt-3 mt-1">
          Analyzed in {result.elapsed_ms}ms · Image not stored
        </p>
      </div>

      {result.recommendations?.length > 0 && (
        <div className="bg-white rounded-2xl p-6 flex flex-col gap-3 shadow-sm border border-slate-100">
          <p className="text-slate-400 text-xs uppercase tracking-wide font-medium">Recommended ingredients</p>
          {result.recommendations.map(r => (
            <div key={r.key} className="flex flex-col gap-0.5">
              <span className="text-slate-900 text-sm font-medium">{r.name}</span>
              <span className="text-slate-500 text-xs">{r.benefit}</span>
            </div>
          ))}
          <p className="text-slate-400 text-xs mt-1 border-t border-slate-100 pt-3">Raw ingredients only · No brand recommendations</p>
        </div>
      )}

      {result.ai_recommendations?.length > 0 && (
        <div className="bg-white rounded-2xl p-6 flex flex-col gap-3 shadow-sm border border-blue-100">
          <div className="flex items-center justify-between">
            <p className="text-slate-400 text-xs uppercase tracking-wide font-medium">Personalised for you</p>
            <span className="text-blue-600 text-xs bg-blue-50 px-2 py-0.5 rounded-full font-medium">AI</span>
          </div>
          {result.ai_recommendations.map((r, i) => (
            <div key={i} className="flex flex-col gap-0.5">
              <span className="text-slate-900 text-sm font-medium">{r.name}</span>
              <span className="text-slate-500 text-xs">{r.benefit}</span>
            </div>
          ))}
          <p className="text-slate-400 text-xs mt-1 border-t border-slate-100 pt-3">Generated by AI · Always consult a dermatologist</p>
        </div>
      )}

      {result.conflicts?.length > 0 && (
        <div className="bg-white rounded-2xl p-6 flex flex-col gap-3 shadow-sm border border-amber-100">
          <p className="text-amber-600 text-xs uppercase tracking-wide font-medium">Ingredient conflicts</p>
          {result.conflicts.map((c, i) => (
            <div key={i} className="flex flex-col gap-1">
              <span className="text-slate-900 text-sm font-medium">
                {c.ingredient_a.replace(/_/g, ' ')} + {c.ingredient_b.replace(/_/g, ' ')}
              </span>
              <span className="text-slate-500 text-xs">{c.reason}</span>
              <span className="text-amber-700 text-xs">{c.timing_advice}</span>
            </div>
          ))}
        </div>
      )}

      <button
        onClick={onRetake}
        className="bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg py-3 text-sm transition-colors"
      >
        Analyze again
      </button>
    </div>
  )
}

function Row({ label, value, className = 'text-slate-900 font-medium capitalize' }) {
  return (
    <div className="flex justify-between items-center">
      <span className="text-slate-500 text-sm">{label}</span>
      <span className={`text-sm ${className}`}>{value}</span>
    </div>
  )
}
