"""add conflict_pairs table and conflicts column to analyses

Revision ID: 40bd0da568a0
Revises: a1b2c3d4e5f6
Create Date: 2026-04-27 21:22:45.452110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bd0da568a0'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conflict_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_a', sa.String(length=100), nullable=False),
    sa.Column('ingredient_b', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timing_advice', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_pairs_id'), 'conflict_pairs', ['id'], unique=False)
    op.create_index(op.f('ix_conflict_pairs_ingredient_a'), 'conflict_pairs', ['ingredient_a'], unique=False)
    op.create_index(op.f('ix_conflict_pairs_ingredient_b'), 'conflict_pairs', ['ingredient_b'], unique=False)
    op.add_column('analyses', sa.Column('conflicts', sa.Text(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'conflicts')
    op.drop_index(op.f('ix_conflict_pairs_ingredient_b'), table_name='conflict_pairs')
    op.drop_index(op.f('ix_conflict_pairs_ingredient_a'), table_name='conflict_pairs')
    op.drop_index(op.f('ix_conflict_pairs_id'), table_name='conflict_pairs')
    op.drop_table('conflict_pairs')
    # ### end Alembic commands ###
